backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: General
        name: general
        format: frontmatter
        file: content/settings/general.md
        fields:
          - { label: Title, name: title, widget: string }

  - label: Blog
    name: blog
    folder: content/blog
    format: frontmatter
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }